# Agrega esta línea al final del archivo para definir la política de seguridad de contenido (CSP) de tu sitio
csp: "default-src 'none'; font-src 'self' https://db.onlinewebfonts.com; ..."

# Reemplaza https://db.onlinewebfonts.com con la URL de la fuente que quieres usar
# Si quieres usar más de una fuente, puedes separarlas con espacios
# Si no quieres usar ninguna fuente externa, puedes eliminar la URL y dejar solo 'self'
# Si quieres permitir cualquier fuente, puedes usar el valor '*'
# Para más información sobre la directiva font-src, visita https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/font-src
